name: deploying-doc
run-name: Deploying doc â€” ${{ github.run_id }}
on:
    schedule:
      - cron: 30 04 * * 1,4

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
          - name: ðŸšš Checkout
            uses: actions/checkout@v4
            with:
              fetch-depth: 0

          - uses: pnpm/action-setup@v4
            name: ðŸ”§Install pnpm
            with:
              version: 9
              run_install: false

          - name: ðŸ”§Install Node.js
            uses: actions/setup-node@v4
            with:
              node-version: 20
              cache: 'pnpm'

          - name: ðŸ”§Install dependencies
            run: pnpm install

          - name: ðŸ”´Build doc
            run: pnpm run docs:build

          - name: ðŸ“‚ Sync files
            uses: SamKirkland/FTP-Deploy-Action@v4.3.5
            with:
              server: ${{ secrets.FTP_SERVER_NAME }}
              username: ${{ secrets.FTP_SERVER_USERNAME }}
              password: ${{ secrets.FTP_SERVER_PASSWORD }}
              local-dir: ./src/.vuepress/dist/
              server-dir: ./jingji/book/